--Step-1: select the database
USE DATABASE RESTAURANT_ANALYTICS;
SELECT CURRENT_DATABASE();

--select the RAW schema
USE SCHEMA RAW;
SELECT CURRENT_SCHEMA();

--Step-2: create the csv file format
CREATE OR REPLACE FILE FORMAT CSV_FORMAT
TYPE = CSV
SKIP_HEADER = 1
FIELD_OPTIONALLY_ENCLOSED_BY = '"'
TRIM_SPACE = TRUE
NULL_IF = ('NULL', 'null', '');
SHOW FILE FORMATS;

--create the internal stage
CREATE OR REPLACE STAGE RESTAURANT_STAGE
FILE_FORMAT = CSV_FORMAT;
SHOW STAGES;

USE DATABASE RESTAURANT_ANALYTICS;
USE SCHEMA RAW;
SELECT CURRENT_DATABASE(), CURRENT_SCHEMA();
