--Step-3: Create RAW TABLES
-- Create RAW_CUSTOMERS
CREATE OR REPLACE TABLE RAW_CUSTOMERS
(
    CUSTOMER_ID      VARCHAR,
    FIRST_NAME       VARCHAR,
    LAST_NAME        VARCHAR,
    EMAIL            VARCHAR,
    PHONE            VARCHAR,
    LOYALTY_TIER     VARCHAR,
    CITY             VARCHAR,
    STATE            VARCHAR,
    COUNTRY          VARCHAR,
    UPDATED_AT       TIMESTAMP_NTZ,

    LOAD_TS          TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    SOURCE_FILE_NAME VARCHAR
);

--create RAW_RESTAURANTS
CREATE OR REPLACE TABLE RAW_RESTAURANTS
(
    RESTAURANT_ID      VARCHAR,
    RESTAURANT_NAME    VARCHAR,
    REGION             VARCHAR,
    CITY               VARCHAR,
    STATE              VARCHAR,
    COUNTRY            VARCHAR,
    OPEN_DATE          DATE,
    SERVICE_MODES      VARCHAR,
    STATUS             VARCHAR,

    LOAD_TS            TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    SOURCE_FILE_NAME   VARCHAR
);

--create RAW_MENU_ITEMS
CREATE OR REPLACE TABLE RAW_MENU_ITEMS
(
    MENU_ITEM_ID       VARCHAR,
    ITEM_NAME          VARCHAR,
    ITEM_TYPE          VARCHAR,
    CUISINE            VARCHAR,
    DIET_TYPE          VARCHAR,
    LIST_PRICE         NUMBER(10,2),
    STATUS             VARCHAR,
    UPDATED_AT         TIMESTAMP_NTZ,

    LOAD_TS            TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    SOURCE_FILE_NAME   VARCHAR
);

--create RAW_ORDERS
CREATE OR REPLACE TABLE RAW_ORDERS
(
    ORDER_ID           VARCHAR,
    ORDER_LINE_ID      VARCHAR,
    ORDER_DATE         DATE,
    CUSTOMER_ID        VARCHAR,
    MENU_ITEM_ID       VARCHAR,
    RESTAURANT_ID      VARCHAR,
    ORDER_CHANNEL      VARCHAR,
    QTY                NUMBER,
    UNIT_PRICE         NUMBER(10,2),
    DISCOUNT_PCT       NUMBER(5,2),
    PAYMENT_TYPE       VARCHAR,
    ORDER_STATUS       VARCHAR,

    LOAD_TS            TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    SOURCE_FILE_NAME   VARCHAR
);
SHOW TABLES;
SELECT TABLE_NAME
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA = 'RAW';
