--RAW DATA RECONCILIATION
SELECT 'RAW_CUSTOMERS' AS TABLE_NAME, COUNT(*) AS ROW_COUNT
FROM RAW_CUSTOMERS

UNION ALL

SELECT 'RAW_RESTAURANTS', COUNT(*)
FROM RAW_RESTAURANTS

UNION ALL

SELECT 'RAW_MENU_ITEMS', COUNT(*)
FROM RAW_MENU_ITEMS

UNION ALL

SELECT 'RAW_ORDERS', COUNT(*)
FROM RAW_ORDERS;

--CHECK FOR DUPLICATE ORDER LINES
SELECT
    ORDER_ID,
    ORDER_LINE_ID,
    COUNT(*) AS RECORD_COUNT
FROM RAW_ORDERS
GROUP BY ORDER_ID, ORDER_LINE_ID
HAVING COUNT(*) > 1;

-- CHECK NULLS IN CRITICAL RAW COLUMNS
SELECT
    COUNT_IF(ORDER_ID IS NULL) AS NULL_ORDER_ID,
    COUNT_IF(ORDER_LINE_ID IS NULL) AS NULL_ORDER_LINE_ID,
    COUNT_IF(CUSTOMER_ID IS NULL) AS NULL_CUSTOMER_ID,
    COUNT_IF(MENU_ITEM_ID IS NULL) AS NULL_MENU_ITEM_ID,
    COUNT_IF(RESTAURANT_ID IS NULL) AS NULL_RESTAURANT_ID,
    COUNT_IF(ORDER_DATE IS NULL) AS NULL_ORDER_DATE
FROM RAW_ORDERS;

--VALIDATE SOURCE FILE METADATA
SELECT
    SOURCE_FILE_NAME,
    COUNT(*) AS ROW_COUNT
FROM RAW_ORDERS
GROUP BY SOURCE_FILE_NAME;

SELECT
    CUSTOMER_KEY,
    CUSTOMER_ID,
    FIRST_NAME,
    LAST_NAME,
    LOYALTY_TIER,
    EFF_START_TS,
    EFF_END_TS,
    IS_CURRENT,
    HASH_DIFF
FROM RESTAURANT_ANALYTICS.DW.DIM_CUSTOMER
LIMIT 10;

--Check fact count
SELECT COUNT(*) AS FACT_COUNT
FROM RESTAURANT_ANALYTICS.DW.FACT_ORDERS;

--Check duplicate order lines
SELECT
    ORDER_ID,
    ORDER_LINE_ID,
    COUNT(*) AS CNT
FROM RESTAURANT_ANALYTICS.DW.FACT_ORDERS
GROUP BY ORDER_ID, ORDER_LINE_ID
HAVING COUNT(*) > 1;

--Check the calculated amounts
SELECT
    ORDER_ID,
    ORDER_LINE_ID,
    QTY,
    UNIT_PRICE,
    DISCOUNT_PCT,
    GROSS_AMOUNT,
    DISCOUNT_AMOUNT,
    NET_AMOUNT
FROM RESTAURANT_ANALYTICS.DW.FACT_ORDERS
LIMIT 10;

SELECT COUNT(*) AS MISSING_KEYS
FROM RESTAURANT_ANALYTICS.DW.FACT_ORDERS
WHERE DATE_KEY IS NULL
   OR CUSTOMER_KEY IS NULL
   OR RESTAURANT_KEY IS NULL
   OR MENU_ITEM_KEY IS NULL;

--Revenue View
SELECT *
FROM RESTAURANT_ANALYTICS.SEMANTIC.V_REVENUE_DAILY
ORDER BY FULL_DATE
LIMIT 10;

--Item Performance
SELECT *
FROM RESTAURANT_ANALYTICS.SEMANTIC.V_ITEM_PERFORMANCE
ORDER BY NET_REVENUE DESC
LIMIT 10;

--Restaurant Performance
SELECT *
FROM RESTAURANT_ANALYTICS.SEMANTIC.V_RESTAURANT_PERFORMANCE
ORDER BY NET_REVENUE DESC
LIMIT 10;
