{{ config(materialized='view') }}

SELECT
    TRIM(ORDER_ID) AS ORDER_ID,
    TRIM(ORDER_LINE_ID) AS ORDER_LINE_ID,
    ORDER_DATE,
    TRIM(CUSTOMER_ID) AS CUSTOMER_ID,
    TRIM(MENU_ITEM_ID) AS MENU_ITEM_ID,
    TRIM(RESTAURANT_ID) AS RESTAURANT_ID,
    UPPER(TRIM(ORDER_CHANNEL)) AS ORDER_CHANNEL,
    QTY,
    UNIT_PRICE,
    DISCOUNT_PCT,
    UPPER(TRIM(PAYMENT_TYPE)) AS PAYMENT_TYPE,
    UPPER(TRIM(ORDER_STATUS)) AS ORDER_STATUS,
    LOAD_TS,
    SOURCE_FILE_NAME
FROM {{ source('raw', 'RAW_ORDERS') }}