{{ config(materialized='view') }}

SELECT
    TRIM(CUSTOMER_ID) AS CUSTOMER_ID,
    TRIM(FIRST_NAME) AS FIRST_NAME,
    TRIM(LAST_NAME) AS LAST_NAME,
    LOWER(TRIM(EMAIL)) AS EMAIL,
    TRIM(PHONE) AS PHONE,
    UPPER(TRIM(LOYALTY_TIER)) AS LOYALTY_TIER,
    TRIM(CITY) AS CITY,
    TRIM(STATE) AS STATE,
    TRIM(COUNTRY) AS COUNTRY,
    UPDATED_AT,
    LOAD_TS,
    SOURCE_FILE_NAME
FROM {{ source('raw', 'RAW_CUSTOMERS') }}