{{ config(materialized='view') }}

SELECT
    TRIM(RESTAURANT_ID) AS RESTAURANT_ID,
    TRIM(RESTAURANT_NAME) AS RESTAURANT_NAME,
    TRIM(REGION) AS REGION,
    TRIM(CITY) AS CITY,
    TRIM(STATE) AS STATE,
    TRIM(COUNTRY) AS COUNTRY,
    OPEN_DATE,
    TRIM(SERVICE_MODES) AS SERVICE_MODES,
    UPPER(TRIM(STATUS)) AS STATUS,
    LOAD_TS,
    SOURCE_FILE_NAME
FROM {{ source('raw', 'RAW_RESTAURANTS') }}