{{ config(materialized='view') }}

SELECT
    TRIM(MENU_ITEM_ID) AS MENU_ITEM_ID,
    TRIM(ITEM_NAME) AS ITEM_NAME,
    UPPER(TRIM(ITEM_TYPE)) AS ITEM_TYPE,
    TRIM(CUISINE) AS CUISINE,
    UPPER(TRIM(DIET_TYPE)) AS DIET_TYPE,
    LIST_PRICE,
    UPPER(TRIM(STATUS)) AS STATUS,
    UPDATED_AT,
    LOAD_TS,
    SOURCE_FILE_NAME
FROM {{ source('raw', 'RAW_MENU_ITEMS') }}