{{ config(materialized='view') }}

SELECT
    ORDER_CHANNEL,
    COUNT(DISTINCT ORDER_ID) AS TOTAL_ORDERS,
    SUM(QTY) AS TOTAL_QTY,
    SUM(GROSS_AMOUNT) AS GROSS_REVENUE,
    SUM(DISCOUNT_AMOUNT) AS DISCOUNT_AMOUNT,
    SUM(NET_AMOUNT) AS NET_REVENUE

FROM {{ ref('fact_orders') }}

GROUP BY ORDER_CHANNEL